spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql:///ashoksankar
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    password: Sravani@123456
c3P0:
  maxSize: 100
  minSize: 10